Add Login and Vote logic as participant (#24)
* Lock to spring-watcher-listen gem patch release

* Bump decidim from 0.27.0 to 0.27.1

* Question & Answers administration

* Add GraphQL API types and specs

- Answers
- Questions
- Election
- Elections

* Update repository in README

* Add Steps controller in admin

* Add missing db directory in gem specification

* Add webpacker configuration for JavaScript

* Add Votes controller for participants

* Add 'Create Wallet' logic in admin

* Use Ethereum Faker in specs

* Don't allow access to Wallet creation if it's already created

* Add 'description' field in Questions

* Add Questions and Answers to seeds

* Fix typo

* Fix typo

* Add 'npm ci' step in GitHub Action workflow CI conf

* Add 'Create Election' step in Admin

* Don't allow editing an Election if it's blocked

* Add 'Create Wallet' system spec

* Normalize i18n files with i18n-tasks

* Add elections counter in admin's component sidebar

* Add missing query for admin's component sidebar

* Add system spec for admin's elections steps controller

* Add generated package-lock.json

* Add Census controller in Admin

* Add system spec

* Add credentials/wallets generation for Census

* Rename CsvDatum model to Voter

* Rename 'csv_data' table to 'voters' and unify migrations

* Add missing frozen_string_literal in migration file

* Add VocdoniVotersType to GraphQL API schema

* Add census logic check in SetupForm

* Use address instead of publicKey for the Census

I made a mistake in the naming. We'll need to change the form/fields/etc
accordingly, as what we need to send to Vocdoni API is the Wallet's Address
and not the Public Key.

Also we refactor a bit this function and introduce async/await, as
the getAddress method from ethers.js Wallet returns a Promise.

* Add validation and types to CensusCredentialForm

* Use the Wallets addresses for Census

Remove the Census textaraea for the demo and use the addresses provided
by the GraphQL API.

* Call explicitly to run method in SetupElection

* Replace wallet "public key" references for "address"

I messed up the naming and what we need to send to Vocdoni API are
addresses, so it's better to rename it accordingly.

* Add missing preffix for Voter factory

* Add 'npm ci' step in GitHub Action workflow CI conf

* Fix bad merge resolutions

* Add login form to Votes#new

* Solve bad git merge

* Bump @vocdoni/sdk package from v0.0.2-alpha to v0.0.3-alpha

* Add deterministic wallet generation for Census

* Add missing preffix for Voter factories

* Add missing preffix for Voter factories

* Add missing attribute from Question factory

This probably comes from a bad merge

* Add missing i18n-tasks gem and spec

* Run i18n-tasks add-missing

* Ignore false detections of i18n-tasks 'unused' command

* Run i18n-tasks normalize

* Add debug message to i18n-tasks unused spec

* Revert "Add debug message to i18n-tasks unused spec"

This reverts commit 82efaaa29ac2dd898992c64b5c9f6a9da0818f8b.

* Remove unused i18n string

* Add Election status changer task

* Add "Vote" and "Vote ended" steps in admin

* Change "Encrypting" messages for "Submitting"

The messages from the Elections module are not 100% correct at least
with the current configuration that we're using in the Vocdoni SDK, so
it's better to correct the copies.

* Remove unecessary partials from Elections module

* Implement partial views for voting with Vocdoni

* Change JavaScript logic of window.Decidim.setupVoteComponent

Until now the PreviewVoteComponent and VoteComponent were retrieved from
the window.Decidim.setupVoteComponent object, and this worked well with
the Decidim approach of having a full page for login (aka census
checking), but this doesn't play nice with the full JavaScript approach
of the Vocdoni SDK, so I needed to change the mount logic.

This also means that we change the logic on when to use the Preview (Fake) voting:
until now this was done by just adding whichever script you needed
(setup-vote.js or setup-preview.js); now we must do it with the
`data-preview` attribute, as that allows us to send the wallet object to
the VoteComponent object in setup-vote.js.

This has implications also with the Census check. If it's on Preview
mode we skip it altogether, but if not we use the isInCensus method from
the Vocdoni SDK to check this.

* Remove unecessary helper voter_id in VotesController

* Fix bug with the vocdoni_election_id on Votes UI

* Fix bug getting the values from the login form

* Improve Votes step help messages in Admin's step

* Show error message when login failed

* Add namespace to Election model call in controllers

* Fix error handling and checking of Census

* Fix exports of JS modules

* Return voteId instead of voteHash after successful vote

* Show radio buttons intead of checkboxes on Questions

* Add system spec for admin's vote preview flow

* Fix parsing the answers for submitting to Vocdoni API

* Improve validation and sanitization of login form

* Remove wrongly added directory packages/

* Run i18n-tasks remove-unused

* Run i18n-tasks normalize

* Fix I18n.t call parameters order

* Add missing preffix for factory

* Fix census generation system spec

* Add jest as an NPM dependency

* Remove random_answers_order parameter from VotesHelper

* Add missing i18n key for decidim.statistics.elections_count

* Add publish/unpublish buttons in Election edit form

* Make the Vocdoni API environment configurable

* Infer the Explorer Vote portal verify link from the evironment

Also:

* Remove useless verify method, as this is done through the Explorer
  Vote portal
* Open the "verify" links on a new tab

* Add a description of the module on the Admin's component manage view

* Refactor SetupForm spec to separate expected messages

* Add check for participatory space published on SetupForm

* Add :with_photos trait on :ready_for_setup trait to Election factory

* Add :minimum_photos check on SetupForm

If we change the code to not send any header if there isn't any photo,
then we have the following error message from the Vocdoni API:

> Error: ValidationError: media.header is a required field

* Fix inconsistency on SetupForm error messages

* Fix system spec

* Fix eslint offenses

* Fix rubocop offenses

* Fix erblint offenses

* Use the conditional assigment operator

Suggested on code review

Co-authored-by: Ivan Vergés <ivan@pokecode.net>

* Add 'voc' namespace on 'accordion' CSS class to avoid collisions

* Fix rubocop offense

---------

Co-authored-by: Ivan Vergés <ivan@pokecode.net>